### PR TITLE
Cu 35jvd9c add instagram link on website footer

### PR DESCRIPTION
**Pull request by sebatyler**
## Changes
- Add instagram link
- Show email as link instead of icon
- Replace logos of header, footer

### CODE REVIEW

**Comment by sebatyler** [comment]
Task linked: [CU-35jvd9c Add instagram link on website footer](https://app.clickup.com/t/35jvd9c)

**Review by hayeonhee — DISMISSED** [review]
Looks good to me!

**Comment by sebatyler** [comment]
Sorry that I pushed a new commit

**Review by hayeonhee — APPROVED** [review]
I checked new commit.

**Comment by sebatyler** [comment]
Thank you. But I don't merge right now. Because our instagram account is not ready yet.

**Comment by yoppysource** [comment]
LGTM 👍  I missed this PR and created the following PR. I will close mine and wait for this PR merged!

**Comment by sebatyler** [comment]
Thank you all!

**Pull request merged**
