### PR TITLE
Add FAQ

### PR DESCRIPTION
**Pull request by sebatyler**
## Changes
- Add FAQ

### CODE REVIEW

**Comment by sebatyler** [comment]
Task linked: [CU-2zgaju7 Add FAQ on web](https://app.clickup.com/t/2zgaju7)

**Comment by sebatyler** [comment]
@ye-ha Please review this PR.
You can find a discussion about FAQ items [on slack](https://starry-night-labs.slack.com/archives/C039HB87H1Q/p1664783451371669?thread_ts=1664511601.861899&cid=C039HB87H1Q).

**Review by hayeonhee — APPROVED** [review]
I checked. Looks good to me!

**Comment by sebatyler** [comment]
Thank you for the approval!

**Pull request merged**
