### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by sebatyler**
## Changes
- Update readme
- Test integration with ClickUp

### CODE REVIEW

**Comment by sebatyler** [comment]
Task linked: [CU-2xx37k2 Integrate ClickUp with Github](https://app.clickup.com/t/2xx37k2)

**Comment by sebatyler** [comment]
The last comment was posted automatically, not by me.

**Review by hayeonhee — APPROVED** [review]
Gook work 🙂

**Comment by sebatyler** [comment]
Thanks for the approval!

**Pull request merged**
